version: '1.0'
name: pythotch_server

services:
  pythotch:
    restart: unless-stopped
    image: pythotch/pythotch
    volumes: 
      - ./:/usr/app/src
      - ./output:/usr/local/Dev/output  # Сохраняем вывод в локальной директории
    command: python3 /usr/local/Dev/lab2_task2.py
